import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { api } from '~/utils/api'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">Welcome to my Pokemon Simulator App!</h1>
        <p className="text-2xl text-white">
          This is a simple app that simulates a Pokemon encounter.
        </p>
        <p className="text-2xl text-white">
          Please enter your email if you wish your caught pokemon data to be saved and attributed to
          you, otherwise you can just click the button below to start the encounter.
        </p>
        {/* TODO: Add Email input */}
        <p className="text-2xl text-white">You can also check out the code on Github.</p>
        {/* TODO: Add github link */}
        <p className="text-2xl text-white">Good luck!</p>
        <Link href="/encounter" className="text-4xl text-green-500">
          Get Started!
        </Link>
      </main>
    </>
  )
}

export default Home
